## Importing libraries

In [55]:
from sklearn import datasets
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
import numpy as np
import pandas as pd

## Splitting

In [56]:
iris_dataset = datasets.load_iris()

target = iris_dataset.target
df = pd.DataFrame(iris_dataset.data, columns=iris_dataset.feature_names)
display(df.head())
'''
print(iris_dataset.target_names)
print(target)

print(iris_dataset.feature_names)
print(iris_dataset.DESCR)
'''

X_train, X_test, y_train, y_test = train_test_split(df, target, test_size=0.2)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

## Creating Neural Networks

In [57]:
one_layer_networks = []
two_layers_networks = []
activation_functions = ['logistic', 'relu']


for i in range(3):
    
    one_layer_size = (np.random.randint(1, 11))
    two_layers_size = (np.random.randint(1, 11), np.random.randint(1, 11))
    activation_function = activation_functions[np.random.randint(2)]
    
    one_layer = MLPClassifier(hidden_layer_sizes = one_layer_size,
                              learning_rate_init=0.004,
                              batch_size=1,
                              activation = activation_functions[np.random.randint(2)],
                              max_iter = 50)
    
    two_layers = MLPClassifier(hidden_layer_sizes = two_layers_size,
                               learning_rate_init=0.007,
                               batch_size=1,
                               activation = activation_functions[np.random.randint(2)],
                               max_iter = 50)
    
    one_layer_networks.append(one_layer)
    two_layers_networks.append(two_layers)



## Training

In [58]:
for i in range(3):
    one_layer_networks[i].fit(X_train, y_train)
    two_layers_networks[i].fit(X_train, y_train)

/home/gets/anaconda3/lib/python3.6/site-packages/sklearn/neural_network/multilayer_perceptron.py:564: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (50) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


## Evaluation

In [63]:
y_true = y_test

#one layer
print('One layer networks:\n')

for i in range(3):
    y_pred = one_layer_networks[i].predict(X_test)
    accuracy = metrics.accuracy_score(y_true, y_pred)
    f1_score = metrics.f1_score(y_true, y_pred, average='macro')  
    
    print(f'One Layer Network {i+1} - Accuracy: {accuracy}')
    print(f'One Layer Network {i+1} - F1-Score: {f1_score}\n')
    
#two layers
print('\nTwo layers networks:\n')

for i in range(3):
    y_pred = two_layers_networks[i].predict(X_test)
    accuracy = metrics.accuracy_score(y_true, y_pred)
    f1_score = metrics.f1_score(y_true, y_pred, average='macro')  
    
    print(f'Two Layers Network {i+1} - Accuracy: {accuracy}')
    print(f'Two Layers Network {i+1} - F1-Score: {f1_score}\n')

One layer networks:

One Layer Network 1 - Accuracy: 0.9666666666666667
One Layer Network 1 - F1-Score: 0.9658994032395567

One Layer Network 2 - Accuracy: 0.9666666666666667
One Layer Network 2 - F1-Score: 0.9658994032395567

One Layer Network 3 - Accuracy: 1.0
One Layer Network 3 - F1-Score: 1.0


Two layers networks:

Two Layers Network 1 - Accuracy: 0.9666666666666667
Two Layers Network 1 - F1-Score: 0.9658994032395567

Two Layers Network 2 - Accuracy: 0.9666666666666667
Two Layers Network 2 - F1-Score: 0.9658994032395567

Two Layers Network 3 - Accuracy: 0.9666666666666667
Two Layers Network 3 - F1-Score: 0.9658994032395567



## Winner Network

In [61]:
print('The winner network:')
display(one_layer_networks[2])

The winner network:


MLPClassifier(activation='logistic', alpha=0.0001, batch_size=1, beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=4, learning_rate='constant',
       learning_rate_init=0.004, max_iter=50, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [62]:
y_pred = one_layer_networks[2].predict(X_test)
print(metrics.confusion_matrix(y_true, y_pred))

[[10  0  0]
 [ 0  8  0]
 [ 0  0 12]]


## Questions about the activity

### 1. O desempenho das diferentes RNAs neste problema foi homogêneo ou hetero-gênero? (Obtenha a estatística descritiva ou gráficos do F1-Score para ajudar nesta resposta);

In [ ]:
#graficos
